/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package moduloPasajero.Jframe;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import moduloAeropuerto.archivosBinarios.EscritorDeAvionesBinarios;
import moduloAeropuerto.archivosBinarios.EscritorDeVueloBinarios;
import moduloAeropuerto.clases.estructuraDeArchivo.Aviones;
import moduloAeropuerto.clases.estructuraDeArchivo.Vuelo;
import moduloAeropuerto.jFrame.VerAsientos;

/**
 *
 * @author dell
 */
public class InformacionVuelo extends javax.swing.JFrame {
    
    private int codigo;
    private String origen;
    private String destino;
    private EscritorDeVueloBinarios EscritorDeVueloBinarios;
    private ArrayList<Vuelo> lisVuelos;
    private ArrayList<Vuelo> Axiliar;
    private Vector<String> vector= new Vector<>();
    private ArrayList<Aviones> lisaviones;
    private EscritorDeAvionesBinarios  escritorDeAvionesBinarios ;
    private int indice;
    public InformacionVuelo(int codigo,String origen, String destino) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.codigo=codigo;
        this.EscritorDeVueloBinarios=new EscritorDeVueloBinarios();
        this.escritorDeAvionesBinarios= new EscritorDeAvionesBinarios();
        this.origen=origen;
        this.destino=destino;
        leerVuelo();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBackground(new java.awt.Color(255, 255, 153));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 32, 649, 61));

        jButton2.setText("Buscar Asientos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 99, -1, -1));

        jButton3.setText("Regresar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 130));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          buscarAvion();
         this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ModuloPasajeros tmp= new ModuloPasajeros();
        tmp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    public void leerVuelo(){
    
        try {
           lisVuelos= this.EscritorDeVueloBinarios.leerVuelos();
           this.lisaviones=this.escritorDeAvionesBinarios.leerAvion();
        } catch (IOException ex) {
            Logger.getLogger(InformacionVuelo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(InformacionVuelo.class.getName()).log(Level.SEVERE, null, ex);
        }
        informacionVuelo();
        
    }
  
     public void informacionVuelo(){
         
        for(int i=0; i<lisVuelos.size();i++){
            if(lisVuelos.get(i).getNombreAerpurtoOrigen().equals(origen)){
                if(lisVuelos.get(i).getNombreAerpurtoDestino().equals(destino)){
                    if(lisVuelos.get(i).getCodigoAvion()==codigo);
                    DefaultTableModel modelo = new DefaultTableModel();
                        this.jTable1.setModel(modelo);
                        this.indice=i;
                         //Anadir columnas
                          modelo.addColumn("Nombre Aeropuerto origen");
                          modelo.addColumn("Nombre Aeropuerto Destino");
                          modelo.addColumn("Precio");
                          modelo.addColumn("Fecha de Salida ");
        
                         modelo.addRow(new Object[]{lisVuelos.get(i).getNombreAerpurtoOrigen(),lisVuelos.get(i).getNombreAerpurtoDestino(),"Q "+lisVuelos.get(i).getPrecioBoleto(),lisVuelos.get(i).getFechaDeSalida()});
                       
                }
            }
        }
     
     }
     public void buscarAvion(){
         
         for(int i=0; i<this.lisaviones.size();i++){
         
          if(lisaviones.get(i).getCodigoAvion()==this.lisVuelos.get(indice).getCodigoAvion()){
               System.out.println(" Existe "+i+"   "+lisaviones.get(i).getCodigoAvion());
               VerAsientos ver =new VerAsientos(i);
              ver.setVisible(true);
              ver.mostrarAsientos(lisaviones.get(i).getFilas(), lisaviones.get(i).getColumnas());
                    
          }
         }
     }
}
